III-4867 Refactor OfferRestBaseController into 10 handlers
cultuurnet/udb3-silex pull request #1125
Opened 2022-09-02 07:20 UTC by JonasVHG

### Added

### Changed

### Removed

### Fixed

---
Ticket: https://jira.uitdatabank.be/browse/III-4867

2022-09-05 09:45 UTC, LucWollants requested changes
I think that the interface `OfferEditingServiceInterface` and the concrete classes `DefaultOfferEditingService` and `EventEditingService` are no longer used because the request handlers dispatch a command directly.

2022-09-05 09:50 UTC, LucWollants commented on src/Http/Offer/AddImageRequestHandler.php
> +            return new JsonResponse(
Maybe throw an ApiProblem here?

2022-09-05 09:56 UTC, LucWollants commented on src/Http/Offer/SelectMainImageRequestHandler.php
> +            return new JsonResponse(
If possible I would already use an `ApiProblem` here.

2022-09-05 09:59 UTC, LucWollants commented on src/Http/Offer/UpdateContactPointRequestHandler.php
> +            return new JsonResponse(
Another candidate for `ApiProblem` instead of a JsonResponse.

2022-09-05 10:02 UTC, LucWollants commented on src/Http/Offer/UpdateOrganizerFromJsonBodyRequestHandler.php
> +            return new JsonResponse(
Another one for `ApiProblem` refactor.

2022-09-05 13:58 UTC, JonasVHG commented
> I think that the interface `OfferEditingServiceInterface` and the concrete classes `DefaultOfferEditingService` and `EventEditingService` are no longer used because the request handlers dispatch a command directly.

Once I'm finished with III-4868, I will do this in a seperate PR: III-4917 because those classes are still used in `EventOrganizerRelationService` & `PlaceOrganizerRelationService`

2022-09-06 06:26 UTC, LucWollants approved these changes

2022-09-06 07:16 UTC, merged