III-4654 export JsonLd with calsum
cultuurnet/udb3-silex pull request #1142
Opened 2022-09-14 09:12 UTC by JonasVHG

### Changed

- Added CalendarSummaryRepositoryInterface to JSONLDEventFormatter

### Fixed

- Exports via JsonLd again have a `calendarSummary`

---
Ticket: https://jira.uitdatabank.be/browse/III-4654

2022-09-15 07:56 UTC, LucWollants commented on src/EventExport/Format/JSONLD/JSONLDEventFormatter.php
> +    private function addCalendarSummary(string $eventId): string
This does a `get`

2022-09-15 07:57 UTC, LucWollants commented on src/EventExport/Format/JSONLD/JSONLDEventFormatter.php
> +            $calendarSummary = $exception->getMessage();
I would leave the summary empty instead of putting the exception message inside the exported JSON.

2022-09-15 08:00 UTC, LucWollants requested changes
I have several general remarks:
- When changing legacy code I would take the effort to keep doing boy scouting work
- Many of the constructor parameters are nullable, but the provider does inject all the parameters, so I would make the parameters required
- There is also this ticket https://jira.uitdatabank.be/browse/III-4913 which advises to use another approach

2022-09-19 12:15 UTC, bertramakers commented
> There is also this ticket https://jira.uitdatabank.be/browse/III-4913 which advises to use another approach

Maybe we can keep using the `CalendarSummaryRepository` in this PR for now, and refactor that to just use the calendar summary library instead of fetching it via HTTP in both export formatters (JSON & Tabular) in III-4913?

2022-09-20 06:22 UTC, LucWollants commented
> > There is also this ticket https://jira.uitdatabank.be/browse/III-4913 which advises to use another approach
> 
> Maybe we can keep using the `CalendarSummaryRepository` in this PR for now, and refactor that to just use the calendar summary library instead of fetching it via HTTP in both export formatters (JSON & Tabular) in III-4913?

Sounds like a good plan. I will do a quick check to see how much work it will be to already replace all the nullable arguments which make the code less readable and maintainable.

2022-09-21 10:05 UTC, LucWollants commented on src/EventExport/CalendarSummary/CalendarSummaryWithFormatterRepository.php
> +    private DocumentRepository $repository;
I think the name can be more explicit, this is an `eventRepository` or `eventJsonRepository`

2022-09-21 10:06 UTC, LucWollants commented on src/EventExport/CalendarSummary/CalendarSummaryWithFormatterRepository.php
> +    public function get(string $offerId, ContentType $type, Format $format): string
I think in this context it is always an `eventId`

2022-09-21 10:13 UTC, LucWollants requested changes
- Do we still use `HttpCalendarSummaryRepository`? If not it can be removed.
- I think we don't test the calendar summary export, would that be possible to test?

2022-09-21 14:44 UTC, LucWollants approved these changes

2022-09-22 06:45 UTC, merged