III-4975 PSR-11 labels
cultuurnet/udb3-silex pull request #1182
Opened 2022-10-05 14:31 UTC by JonasVHG

### Added

### Changed

### Removed

### Fixed

---
Ticket: https://jira.uitdatabank.be/browse/III-4975

2022-10-06 08:41 UTC, bertramakers requested changes

2022-10-06 08:41 UTC, bertramakers commented on app/Labels/LabelServiceProvider.php
> +                $labels = file_exists(__DIR__ . '/../../../config.excluded_labels.php') ? require __DIR__ . '/../../../config.excluded_labels.php' : [];
```suggestion
                $labels = file_exists(__DIR__ . '/../../config.excluded_labels.php') ? require __DIR__ . '/../../config.excluded_labels.php' : [];
```
File location has changed so this path needs to change as well

2022-10-06 08:42 UTC, bertramakers commented
Other changes look good! I'd like to get rid of all these constants for the service names though, but we'll do that later in the general cleanup of service names to use FQN's as much as possible

2022-10-06 09:02 UTC, bertramakers approved these changes
Perfect now! 👌

2022-10-07 11:28 UTC, bertramakers commented
@JonasVHG remember to merge this. There are some merge conflicts now

2022-10-07 11:55 UTC, JonasVHG commented
> @JonasVHG remember to merge this. There are some merge conflicts now



> @JonasVHG remember to merge this. There are some merge conflicts now

Sorry, I've overlooked this a bit with my many meetings yesterday. I've finished the merge and am running the acceptance tests atm.

2022-10-07 13:41 UTC, merged